### ISSUE TITLE
When I am trying to put an animation it shows "animation does not have any text" when it does in console

### ISSUE THREAD

**Issue by Teddy293** [NEZNAMY/TAB#1165]
### Server version

Spigot 1.20.2

### TAB version

4.1.0

### Describe the bug

When I am putting an animation in the console through the animations area and i have in the config set for an animation to be in the footer it just says that there is no text in the animation even though in the animations area I can see that there is text. I've tried reading the wiki but I don't really see anything different.
![image_2023-12-06_162318957](https://github.com/NEZNAMY/TAB/assets/153133860/ab300ffe-c6b6-436d-9268-d4ae426f7d5f)

Sorry I didn't put this the first time
https://pastebin.com/HzNDhXST
Here is the config if needed
https://pastebin.com/6egDPvFN
### Expected behavior

I am trying to create like a "progressbar" that like when it fills up it changes through different things on the footer on tab like (discord) (store) (voting)

### Steps to reproduce

I'm not sure 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You did not even send your animations.yml file. I cannot check your file if you do not send it.

**Comment by Teddy293** [comment]
> You did not even send your animations.yml file. I cannot check your file if you do not send it. Make sure to also use some paste website, since pasting config here will result in markdown formatting totally destroying the content and making it unreadable.

it is there now sorry about that

**Comment by NEZNAMY** [comment]
Are you sure you uploaded the file to the server correctly? What does plugin's startup log say in console? Which animation are you trying to use?

**Comment by Teddy293** [comment]
> Line 55 says "text" instead of "texts".

... Thank you, sorry if I wasted your time
