### ISSUE TITLE
CPU usage tracking

### ISSUE THREAD

**Issue by kforbro** [NEZNAMY/TAB#1237]
### Server version

Pufferfish 1.20.1

### TAB version

4.1.3 build #1052

### Evidence

CPU usage tracking still has an impact on performance even if `/tab cpu` has not been used

### Additional info

300 players:
![Снимок экрана 2024-02-28 в 15 09 51](https://github.com/NEZNAMY/TAB/assets/39985355/fd05d0e8-41fb-4fb6-b992-c42a389ce53a)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
Command preprocess is for bossbar / scoreboard toggle commands. It cannot be async, because they might need to cancel the event (since toggle commands are not real commands, you don't want the actual commands to run as they don't exist).
This has nothing to do with /tab cpu tracking.

**Comment by kforbro** [comment]
> Command preprocess is for bossbar / scoreboard toggle commands. It cannot be async, because they might need to cancel the event (since toggle commands are not real commands, you don't want the actual commands to run as they don't exist). This has nothing to do with /tab cpu tracking.

Why don't you want to register these commands?

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/48e3d0f4-3107-4d6a-98c6-405651e04778)

**Comment by kforbro** [comment]
Got it, thanks. If you have the time and desire, you can use some command libraries that allow to register commands without adding them to plugin.yml, so they can be configurable.

By the way, it seems to me FeatureManager#onCommand performs a lot of unneeded actions if it is suited only for commands
![Снимок экрана 2024-02-28 в 15 37 58](https://github.com/NEZNAMY/TAB/assets/39985355/bd526bbd-46b7-4049-92eb-f6a856788c9d)

**Comment by NEZNAMY** [comment]
I am not interested in using any external libraries for registering commands (and then unregistering them on reload if toggle command is changed or something). I can optimize it though.
You can send the spark report anywhere, you could have opened a ticket on customer discord as well.

**Comment by NEZNAMY** [comment]
Do you actually have scoreboard/bossbar features enabled? If not, it should be fixed now.

**Comment by kforbro** [comment]
> Do you actually have scoreboard/bossbar features enabled? If not, it should be fixed now.

both enabled

**Comment by NEZNAMY** [comment]
Try new build.
