### ISSUE TITLE
IA Ranks

### ISSUE THREAD

**Issue by GWDdoS** [NEZNAMY/TAB#1251]
### TAB version

4.1.2

### Software causing compatibility issue

IA Ranks not appearing and i cant edit the config of TABS without breaking tabs. also the wiki no work 💀 

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
* What is IA?
* You can edit the config. If you weren't able to, everyone would notice, don't you think?
* How is wiki not working? I opened it and can browse it just fine

**Comment by GWDdoS** [comment]
So IA items adder, and i am using the ranks addon. It the IA wiki it says how to make tabs and IA work togehert, although, its wrong and when you do what the wiki says, tab brakes saying delete line 156 etc. (the line were the edit is)

**Comment by GWDdoS** [comment]
https://itemsadder.devs.beer/plugin-usage/adding-content/ranks-textures-prefix

**Comment by NEZNAMY** [comment]
Sounds like you broke yaml syntax. I can't even fix it for you, because you didn't send your config or even the error you got.
The link to itemsadder wiki you sent appears to be working. What do you mean by wiki not working then?

**Comment by GWDdoS** [comment]
I wiki says to add the   Admin:
    tabprefix: '%img_admin%  '
    tagprefix: '%img_admin%  '
but if you do, the tabs conifg breaks and does not work

**Comment by GWDdoS** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/132668764/8a01727f-8da6-4c7d-957c-cc44f4928ee9)

**Comment by GWDdoS** [comment]
if i add the Admin:
tabprefix: '%img_admin% '
tagprefix: '%img_admin% ' it breakes

16.03 21:43:39 [Server] [INFO] [TAB] [[WARN]] File plugins/TAB/config.yml has broken syntax.
16.03 21:43:39 [Server] [INFO] [TAB] Error message from yaml parser: while parsing a block mapping
16.03 21:43:39 [Server] [INFO] in 'reader', line 133, column 5:
16.03 21:43:39 [Server] [INFO] default:

**Comment by NEZNAMY** [comment]
You probably didn't add it into groups.yml like you should, but into config.yml somewhere to break the syntax. I can't know without seeing full config.

**Comment by NEZNAMY** [comment]
Config, the file you broke. Although you were supposed to add it to groups.yml which you didn't.

**Comment by GWDdoS** [comment]
Tahnk you SOO much!

**Comment by NEZNAMY** [comment]
Huh? I didn't fix the supposed compatibility issue still.

**Comment by LuluxClient** [comment]
don't use placeholders use a specific symbol to display the rank. for example in itemsadder you can add an UTF-8 symbol and you will use that in tab & luckperms. It's not a tab issue but a configuration issue @NEZNAMY you can close this issue since it's totally unrelated to your plugin.

**Comment by LuluxClient** [comment]
Example:
```YAML
smile:
  permission: ranks.admin
  show_in_gui: false
  path: "ranks/admin.png"
  symbol: "鄿"
  scale_ratio: 9
  y_position: 8
  ```
  
  and now when typing ANYWHERE the "鄿" symbol it will display your admin rank tab and it can be used litteraly everywhere; if you put it in luckperms when outputting the %luckperms_prefix% placeholder it will show the correct tag

**Comment by Tree182** [comment]
Add a color code before it. That made it work for me.

For example:

tabprefix: '&f%img_admin% '
tagprefix: '&f%img_admin% '
