### ISSUE TITLE
 In 1.8.9 it doesn't show full text

### ISSUE THREAD

**Issue by Amirmg086** [NEZNAMY/TAB#1270]
### Server version

1.20.4

### TAB version

4.1.2

### Describe the bug

In 1.8.9 it doesn't show full ```play.icecraft.ir```

### Expected behavior

In 1.8.9 it doesn't show full ```play.icecraft.ir```

### Steps to reproduce

In 1.8.9 it doesn't show full ```play.icecraft.ir```

### Checklist

- [x] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Amirmg086** [comment]
![Uploading Screenshot_3.png…]()

**Comment by NEZNAMY** [comment]
* 
![image](https://github.com/NEZNAMY/TAB/assets/6338394/195147eb-dd80-46c9-ab23-f6099ade7ba6)
* I am not joining your server. Explain your issue.
* Your screenshot did not upload.

**Comment by Amirmg086** [comment]
In the config I have written ```- '&7| &bPlay.IceCraft.IR'```
But it shows this in game with 1.8.9
```Play.IceCr```

**Comment by NEZNAMY** [comment]
Send your config and screenshot from game.

**Comment by Amirmg086** [comment]
```# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml
header-footer:
  enabled: true
  header:
  - '&7&m                  &7[ &3Ice&bCraft&7 ]&7&m                  '
  - ''
  - '&bServer &8➥ &fLobby'
  - ''
  footer:
  - ''
  - '&bSite: &fIceCraft.IR'
  - '    &bDiscord: &fdiscord.gg/IceCraft'
  - ''
  - '&7&m                                                            '
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  disable-condition: '%world%=disabledworld'
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  invisible-nametags: false
  anti-override: true
  enable-collision: true
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    space-between-lines: true
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-condition: '%world%=disabledworld'
  case-sensitive-sorting: true
  sorting-types:
  - GROUPS:founder,owner,dev,admin,t-developer,srmod,mod,jrmod,sponsor,srhelper,helper,jrhelper,builder,streamer,media,icemaster,blizzard,polar,frozen,arctic,glacier,frostbite,chill,snowflake,default
  - PLACEHOLDER_A_TO_Z:%player%
  disable-condition: '%world%=disabledworld'
  can-see-friendly-invisibles: false
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&c❤'
  disable-condition: '%world%=disabledworld'
  fancy-display-default: NPC
  fancy-display-players: '&c%health%'
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: RED
      progress: '100'
      text: '%animation:bossbar%'
      announcement-bar: false
scoreboard:
  enabled: true
  toggle-command: /scoreboard
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  disable-in-worlds:
  - disabledworld
  delay-on-join-milliseconds: 0
  scoreboards:
    normal:
      title: '&b&lLOBBY'
      lines:
      - '      &7%date%'
      - ''
      - '&8● &bPlayer: &f%player%'
      - '&8● &bRank: &f%luckperms_prefix%'
      - '&8● &bDust: &f%gadgetsmenu_mystery_dust%'
      - ''
      - '&8● &bGlobal: &f%bungee_total%'
      - '&8● &bLobby: &f%bungee_lobby%'
      - '&8● &bSurvival: &f%bungee_survival%'
      - '&8● &bTheBridge: &f%bungee_thebridge%'
      - '&8● &bThePit: &f%bungee_thepit%'
      - '&8● &bBedwars: &f%bungee_bedwars%'
      - '&8● &bSG Land: &f%bungee_sgland%'
      - ''
      - '&7| &bPlay.IceCraft.IR'
    twscoreboard:
      title: TestWorld
      lines:
      - This is scoreboard for everyone in testworld world
      display-condition: '%world%=testworld'
  respect-other-plugins: true
prevent-spectator-effect:
  enabled: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%tps%':
    '20': ''
conditions:
  health:
    conditions:
    - '%health%<21'
    - '%health%>15'
    type: AND
    true: Healthy!
    false: Damaged!
placeholders:
  afk-yes: ' #FF4848&lAFK'
  afk-no: ''
  date-format: dd/MM/yyyy
  time-format: h:mm a
  time-offset: 0
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 500
assign-groups-by-permissions: false
primary-group-finding-list:
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: true
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby3
    - world_nether
    - world_end
    - lobby2
    minigames:
    - paintball
    - bedwars
layout:
  enabled: false
global-playerlist:
  enabled: false
use-online-uuid-in-tablist: true
playerlist-objective:
  enabled: false
  value: ''
  disable-condition: '%world%=disabledworld'
  fancy-value: '&7Ping: %ping%'
ping-spoof:
  enabled: false
``` 
![Uploading Screenshot_3.png…]()

**Comment by NEZNAMY** [comment]
Why do you send your message before screenshot uploads every single time?

**Comment by Amirmg086** [comment]
https://mega.nz/file/cbQVXQoC#xKc_Nyx65avcAeqPQBcJdWmX-XPaBDzNhTi5nHTWyfc

**Comment by NEZNAMY** [comment]
Are you by accident using ViaVersion on BungeeCord?

**Comment by Amirmg086** [comment]
Yes, I have viaversion on Bungeecord

**Comment by Amirmg086** [comment]
What is wrong ?

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/2f4aec25-da06-47b8-964a-c5c42eaf2cad)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/bcc6c16f-50ca-4efd-bcaa-431a067c89f8)
The wiki very clearly explains this compatibility issue, what is causing it, how to solve it and what kind of issues you will get. You completely ignored it. This is not a bug. Plugin works as described. You abused the issue tracker to get free priority help.

**Comment by Amirmg086** [comment]
Can you give me a link to this image or tell me what to do to get it?

**Comment by NEZNAMY** [comment]
It literally says `Install it on all backend servers instead for optimal experience.`
https://github.com/NEZNAMY/TAB/wiki/Compatibility#compatibility-issues
https://github.com/NEZNAMY/TAB/wiki/Additional-information#differences-1

**Comment by Amirmg086** [comment]
That means I have to put the tab on velocity, so that the scoreboards of all servers will be the same

**Comment by NEZNAMY** [comment]
Once again, you a re supposed to install ViaVersion on backend servers instead.

**Comment by Amirmg086** [comment]
i installed viaversion on all servers

**Comment by NEZNAMY** [comment]
If you also deleted it from proxy, your problems are solved now.

**Comment by Amirmg086** [comment]
Should I remove viaversion from the proxy?
